### ISSUE TITLE
[issue] Slot detail view, slot name value resets on page load

### ISSUE THREAD

**Issue by jwfwessels** [praekelt/django-composer-prk#1]
## Context:
When creating a slot or when changing an existing slot. The value of the second field *Slot name:* defaults to the value `content`. This results in erroneously changing the slot type to content when changing other data on the slot.

I also noted that it would probably make more sense for this field's label to read Slot Type?

![image](https://cloud.githubusercontent.com/assets/1531788/22009459/0ca2bbf8-dc8c-11e6-94e4-69e694ff3968.png)

## Expectation:

1. Slot name Field should preserve selected value across page loads 👍 

2. Slot label should be changed Slot Type

**Comment by jbeyers** [comment]
Slot position might be a better name.
